### ISSUE TITLE
TileMill Alternative?

### ISSUE THREAD

**Issue by xaranke** [tmcw/mapmakers-cheatsheet#7]
Mapbox has officially retired TileMill and I was wondering if there was a more current alternative out there. Thanks!

**Comment by tmcw** [comment]
[Kosmtik](https://github.com/kosmtik/kosmtik) is one alternative. TileMill is still available, but it's no longer under Mapbox's support umbrella - if the open source community were to adopt it, it wouldn't be retired anymore. But unfortunately, that rarely happens. In terms of development, Kosmtik is somewhat more of a modern thing.
