### ISSUE TITLE
Add Dinamica EGO to softwares that can convert maps.

### ISSUE THREAD

**Issue by razor85** [tmcw/mapmakers-cheatsheet#9]
In the page https://github.com/tmcw/mapmakers-cheatsheet#a-format-that-i-cant-read, SAFE FME is recommended, but Dinamica EGO http://www.dinamicaego.com can also convert map files. Dinamica EGO is free (even for commercial purposes), has a GNU/Linux version and can convert lots of file types (Just plug a Load Map in to a Save Map functor).

**Comment by tmcw** [comment]
Thanks for the suggestion! It looks like Dinamica is quite a bit more than a format converter, and is mostly a land change model and environmental modeling. I would rather suggest something that's commonplace (like OGR and GDAL as currently suggested) and does format conversion as its main task.
